language: c

before_script:
  - "sudo apt-get -qq update"
  - "sudo apt-get -qq install lib32z1 || true"
  - "curl -s \
       http://adamdunkels.github.io/contiki-fork/mspgcc-4.7.0-compiled.tar.bz2 \
         | tar xjf - -C /tmp/ && sudo cp -f -r /tmp/msp430/* /usr/local/ && rm -rf /tmp/msp430 && msp430-gcc --version || true"

script:
#  - scons board=python toolchain=gcc    oos_openwsn
#  - scons board=telosb toolchain=mspgcc verbose=1 oos_openwsn
 - scons board=gina toolchain=mspgcc verbose=1 oos_openwsn
